#!/usr/bin/env bash
# Convert Quarto notebooks to Jupyter notebooks
# (although note that they can be run in Jupyter directly via jupytext)
set -euo pipefail # Fail fast if needed

for f in tut_*.qmd; do
    quarto convert "$f"
done
