#!/bin/bash

export SCIRIS_BACKEND='agg' # Don't open up figures

# To use pytest-xdist (more robust), use -n auto; to use pytest-parallel (faster), use --workers=auto
method=${1:-robust}
if [ $method == "fast" ]; then
    parallel='--workers=auto'
else
    parallel=' -n auto'
fi

echo 'Running tests...'
pytest -v test_*.py --cov-config=.coveragerc --cov=../sciris --durations=0 $parallel

echo 'Creating HTML report...'
coverage html

echo 'Running report...'
coverage report

echo 'Report location:'
echo "`pwd`/htmlcov/index.html"
