#!/bin/bash
# Run the integration tests Requires pytest-parallel or pytest-xdist:
#   pip install pytest-parallel pytest-xdist

# To use pytest-xdist (more robust), use -n auto; to use pytest-parallel (faster), use --workers=auto
# parallel=' -n auto'
parallel='--workers=auto'

pytest test_*.py $parallel --ignore=manual --durations=0
