'''
Test the machine-readable API index (docs/api.json, docs/llms.txt), which is generated by docs/make_api.py.
'''

import sys
import sciris as sc

sys.path.insert(0, str(sc.thispath(__file__).parent / 'docs')) # The generator lives in the docs folder
import make_api # noqa


#%% Test the index

def test_make_index():
    sc.heading('Test generating the API index')

    index = make_api.make_index()
    entries = index['entries']
    names = [entry['name'] for entry in entries]

    print(f'Index has {len(entries)} entries for v{index["version"]}')
    assert len(entries) > 200, 'Expecting the index to cover most of the Sciris API'
    assert index['version'] == sc.__version__
    assert names == sorted(names, key=str.lower), 'Entries should be sorted by name, for stable diffs'
    assert len(names) == len(set(names)), 'Entries should be unique'

    print('Checking entries')
    for entry in entries:
        name = entry['name']
        assert hasattr(sc, name), f'sc.{name} is in the index but not in the Sciris namespace'
        assert entry['kind'] in ['function', 'class'], f'Unexpected kind for sc.{name}'
        assert entry['signature'].startswith('('), f'Invalid signature for sc.{name}'
        assert entry['summary'], f'No summary for sc.{name}'

    print('Checking aliases')
    for alias,canonical in index['aliases'].items():
        assert getattr(sc, alias) is getattr(sc, canonical), f'sc.{alias} should be an alias for sc.{canonical}'
        assert alias not in names, f'Alias sc.{alias} should not have its own entry'
    assert index['aliases']['saveobj'] == 'save', 'Expecting sc.saveobj to be an alias for sc.save'

    print('Checking known entries')
    entrydict = {entry['name']:entry for entry in entries}
    assert 'series' in entrydict['findnearest']['signature']
    assert entrydict['findnearest']['example'], 'Expecting sc.findnearest() to have an example'
    assert not entrydict['findnearest']['deprecated']
    assert entrydict['dataindex']['deprecated'], 'Expecting sc.dataindex() to be marked as deprecated'

    return index


def test_llms_txt():
    sc.heading('Test generating llms.txt')

    index = make_api.make_index()
    for examples in [False, True]:
        text = make_api.make_llms_txt(index, examples=examples)
        assert text.startswith(f'# Sciris v{sc.__version__}')
        assert '## Math and arrays (sc_math)' in text
        assert '`sc.findnearest' in text
        for entry in index['entries']: # Every entry should appear
            assert f'`sc.{entry["name"]}(' in text, f'sc.{entry["name"]} is missing from llms.txt'
        print(f'llms.txt (examples={examples}): {len(text)/1e3:0.1f} kB')

    full = make_api.make_llms_txt(index, examples=True)
    assert len(full) > len(make_api.make_llms_txt(index, examples=False)), 'Expecting examples to make the file longer'

    return full


def test_generated_index():
    sc.heading('Test the generated API index')

    index = make_api.load()
    assert index['version'] == sc.__version__
    assert index['n_entries'] == len(index['entries'])

    print('Checking that the generated artifacts are up to date')
    stale = make_api.check()
    assert not stale, f'API artifacts are out of date: {stale}. Run "cd docs && python make_api.py" to regenerate.'

    return index


#%% Run as a script
if __name__ == '__main__':
    T = sc.timer()

    index = test_make_index()
    text = test_llms_txt()
    generated = test_generated_index()

    T.toc('Done.')
