#!/bin/bash
# Set up the conda environments for use with run_regression
# Warning: if anything goes wrong, this script can seriously
# mess up your Python environment! Use with caution.
# Version: 2023aug06

# Enable all conda commands
start=`date +%s`
eval "$(conda shell.bash hook)"

for year in 2021 2022 2023; do
    echo "Working on $year..."
    name=sciris$year
    conda env create -f $name-01-01.yml -y 
    conda activate $name
    pip install -r ../requirements.txt # Install test requirements
    pip install -e ../.. # Install Sciris itself
done

end=`date +%s`
echo "Done after $((end-start)) seconds."