#!/bin/bash
# Set up the conda environments for use with run_regression

# Enable all conda commands
start=`date +%s`
eval "$(conda shell.bash hook)"

for year in 2021 2022 2023; do
    echo "Working on $year..."
    name=sciris$year
    conda create -n $name python=3.9 -y 
    conda activate $name
    pip install -r requirements_$year-01-01.txt # Install this year's specific versions
    pip install -r ../requirements.txt # Install test requirements
    pip install -e ../.. # Install Sciris itself
done

end=`date +%s`
echo "Done after $((end-start)) seconds."