project:
  type: website
  output-dir: _build
  title: "Sciris"
  execute-dir: file

website:
  title: "Sciris"
  image: /assets/sciris-logo-grey-small.png
  favicon: /assets/favicon.ico
  # google-analytics: "GTM-NK4K647"

  repo-url: https://github.com/sciris/sciris
  repo-actions: [issue]
  page-navigation: true
  search:
    type: overlay

  page-footer:
    center: "The docs were built for Sciris v{{< var version >}} ({{< var versiondate >}}).<br>© 2014–2025, Sciris Development Team."
    right:
      - icon: github
        href: https://github.com/sciris/sciris
        aria-label: GitHub
      - icon: envelope-at-fill
        href: mailto:info@sciris.org
      - icon: globe
        href: https://sciris.org/

  navbar:
    logo: /assets/sciris-logo-grey-small.png
    title: false
    collapse-below: lg

    tools:
      - icon: github
        href: https://github.com/sciris/sciris
      - icon: envelope-at-fill
        href: mailto:info@sciris.org
      - icon: globe
        href: https://sciris.org

    left:
      - href: index.qmd
        text: Home
      - href: whatsnew.qmd
        text: What's new
      - href: tutorials/index.qmd
        text: Tutorials
      - href: conduct.qmd
        text: Code of conduct
      - href: contributing.qmd
        text: Contributing
      - href: api/index.qmd
        text: API reference

  sidebar:
    - id: main
      collapse-level: 3
      contents:
        - href: index.qmd
          text: "**Home**"
        - href: whatsnew.qmd
          text: "**What's new**"
        - href: api/index.qmd
          text: "**API reference**"
        - section: "**Tutorials**"
          contents:
            - tutorials/tut_intro.ipynb
            - tutorials/tut_arrays.ipynb
            - tutorials/tut_dicts.ipynb
            - tutorials/tut_files.ipynb
            - tutorials/tut_printing.ipynb
            - tutorials/tut_plotting.ipynb
            - tutorials/tut_parallel.ipynb
            - tutorials/tut_dates.ipynb
            - tutorials/tut_utils.ipynb
            - tutorials/tut_advanced.ipynb
        - href: conduct.qmd
          text: "**Code of conduct**"
        - href: contributing.qmd
          text: "**Contributing**"
    - id: api
      collapse-level: 2
      contents:
        - href: index.qmd
          text: "**Home**"
        - href: api/index.qmd
          text: "**API reference**"
        - section: "**Basics**"
          contents:
            - api/sc_asd.qmd
            - api/sc_colors.qmd
            - api/sc_dataframe.qmd
            - api/sc_datetime.qmd
            - api/sc_fileio.qmd
            - api/sc_math.qmd
            - api/sc_nested.qmd
            - api/sc_odict.qmd
            - api/sc_parallel.qmd
            - api/sc_plotting.qmd
            - api/sc_printing.qmd
            - api/sc_profiling.qmd
            - api/sc_settings.qmd
            - api/sc_utils.qmd
            - api/sc_versioning.qmd

format:
  html:
    theme: 
      light: [cosmo, ./assets/styles-light.scss]
      dark: [cosmo, ./assets/styles-dark.scss]
    css: ./assets/styles.css
    toc: true
    toc-depth: 3
    highlight-style: github

filters:
  - interlinks

interlinks:
  fast: true
  sources:
    python:
      url: https://docs.python.org/3/
    numpy:
      url: https://numpy.org/doc/stable/
    pandas:
      url: https://pandas.pydata.org/pandas-docs/stable/
    scipy:
      url: https://docs.scipy.org/doc/scipy/
    matplotlib:
      url: https://matplotlib.org/stable/

quartodoc:
  package: sciris
  title: API reference
  style: pkgdown
  dir: api
  parser: google
  render_interlinks: true
  sections:
    - title: API reference
      desc: Full details on all Sciris classes and functions.
      contents:
        - sc_asd
        - sc_colors
        - sc_dataframe
        - sc_datetime
        - sc_fileio
        - sc_math
        - sc_nested
        - sc_odict
        - sc_parallel
        - sc_plotting
        - sc_printing
        - sc_profiling
        - sc_settings
        - sc_utils
        - sc_versioning

jupyter: python3
execute:
  enabled: false # NB, this is controlled via build_docs
  daemon: true  # Use Jupyter daemon mode
  cache: true   # Cache execution results
  freeze: false # Use caching rather than freezing to store results
  error: false
  echo: true
  warning: true
  kernel: python3