# Note: this workflow only runs manually or on pushes to tagged versions.

name: Publish docs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    name: Quarto
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Sciris
      run: |
        pip install -e .
        pip install -r docs/requirements.txt

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install Quarto interlinks
      working-directory: ./docs
      run: quarto add sciris/quartopydoc --no-prompt

    - name: Publish docs
      working-directory: ./docs
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        ./publish
