# Test that the docs build successfully on pushes to main and PRs targeting main.

name: Test docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Render
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Sciris
      run: |
        pip install -e .
        pip install -r docs/requirements.txt

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install Quarto interlinks
      working-directory: ./docs
      run: quarto add machow/quartodoc --no-prompt

    - name: Render docs
      working-directory: ./docs
      run: ./render
