name: Sciris CI
on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  install_and_test:
    timeout-minutes: 8
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.9'
          - os: ubuntu-latest
            python-version: '3.13'
          - os: ubuntu-latest
            python-version: '3.14'
          - os: windows-latest
            python-version: '3.13'
          - os: macos-latest
            python-version: '3.13'
    runs-on: ${{ matrix.os }}

    name: Tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Sciris
        run: pip install -e .
      - name: Install tests
        working-directory: ./tests
        run: pip install -r requirements.txt
      - name: Run API tests
        working-directory: ./tests
        run: pytest --durations=0 --junitxml=test-results.xml # Run actual tests
      - name: Upload test results
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: './tests/test-results.xml'
          check_name: 'Test Report (${{ matrix.os }} ${{ matrix.python-version }})'
