name: Sciris CI tests
on:
  workflow_dispatch:
  pull_request:

jobs:
  install_and_test:
    timeout-minutes: 8
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.9'
          - os: ubuntu-latest
            python-version: '3.12'
          - os: ubuntu-latest
            python-version: '3.13'
          - os: windows-latest
            python-version: '3.12'
          - os: macos-latest
            python-version: '3.12'
    runs-on: ${{ matrix.os }}
    name: CI tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Sciris
        run: pip install -e .
      - name: Install tests
        working-directory: ./tests
        run: pip install -r requirements.txt
      - name: Run API tests
        working-directory: ./tests
        run: pytest --durations=0 --junitxml=test-results.xml # Run actual tests
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test_results
          path: tests/test-results.xml
